### ISSUE TITLE
I don't suppose the tables are available?

### ISSUE THREAD

**Issue by countbytedown** [inAudible-NG/tables#2]

**Comment by vincurekf** [comment]
The usage part is a bit misleading. You need to:

- clone this repository `git clone https://github.com/inAudible-NG/tables.git`
- cd to the folder and `make`
- then run `./rcrack . -h 999a6ab8...`

The rcrack is included, so you need only this repository.

Maybe you'd need to install dependencies (I had to):
`sudo apt install libpcap-dev libssl-dev openssl`

After that I got it working.

**Comment by inAudible-NG** [comment]
@countbytedown The `*.rtc` files included in this repository are the tables you are looking for.

@vincurekf Thanks for chiming in. I will simplify the documentation a bit. Writing 100% foolproof documentation is hard.

**Comment by countbytedown** [comment]
Thanks for clarification. I have things working now.
